### ISSUE TITLE
Having Issues Getting ElasticBeanstalk Version to Work

### ISSUE THREAD

**Issue by ninjada** [awslabs/amazon-kinesis-scaling-utils#28]
Hello,

Currently testing this with some of my Kinesis streams, with the elasticbeanstalk method. 

Have referenced https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/6 but unfortunately, I appear to have exhausted all troubleshooting and experimentation to get things working.

Have deployed single instance ElasticBeanstalk app with tomcat server and the included .war file from the dist folder.

Using the following config, stored on an s3 bucket:

```
[
    {
        "streamName": "mystream",
        "region": "ap-southeast-2",
        "scaleOnOperation": "PUT",
        "minShards": 1,
        "maxShards": 8,
        "refreshShardsNumberAfterMin": 2,
        "snsArn": "....",
        "scaleUp": {
            "scaleThresholdPct": 75,
            "scaleAfterMins": 2,
            "scalePct": 50
        },
        "scaleDown": {
            "scaleThresholdPct": 50,
            "scaleAfterMins": 2,
            "scalePct": 50,
            "coolOffMins": 2
        }
    },
    {
        "streamName": "mystream",
        "region": "ap-southeast-2",
        "scaleOnOperation": "GET",
        "minShards": 1,
        "maxShards": 8,
        "refreshShardsNumberAfterMin": 2,
        "snsArn": "....",
        "scaleUp": {
            "scaleThresholdPct": 75,
            "scaleAfterMins": 2,
            "scalePct": 50
        },
        "scaleDown": {
            "scaleThresholdPct": 50,
            "scaleAfterMins": 2,
            "scalePct": 50,
            "coolOffMins": 2
        }
    }
]
```

Unfortunately, the only info I can glean from the logs on the eb server is that it successfully got the config-file-url from s3 and started with it. Aside from that, I can't detect anything in the logs that it is otherwise working. But the number of shards on my test stream never changes and I've tried to set the scaleUp & Down ranges to be pretty extreme so that it should trigger. I've even tried on a not-in-use stream, that I'd assume should automatically trigger scaleDowns.

My IAM roles applied to the elastic beanstalk server have the following policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kinesis:Get*",
                "kinesis:List*",
                "kinesis:Describe*",
                "kinesis:MergeShards",
                "kinesis:SplitShard"
            ],
            "Resource": "....:stream/mystream"
        },
        {
            "Action": [
                "sns:Publish"
            ],
            "Effect": "Allow",
            "Resource": "...."
        },
        {
            "Action": [
                "cloudwatch:GetMetricStatistics"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "..../*"
        }
    ]
}
```

Any glaring faults with those configs & policies? Or ideas on how to further debug from the logs to see why this is or isn't working?

**Comment by Yoouuu** [comment]
Hi I'm facing the same issue. After I set up everything, I only see in the log that the stream monitor for my stream is created and started, but then it somehow gets terminated without any error or exception messages. I checked the aws documents to seek for instructions on setting log level to DEBUG so I can troubleshoot. But it turns out that the best place to config log is in source code. It would be nice if someone could add a .ebextensions config file or change the log level in source code from DEBUG to INFO/ERROR?

**Comment by IanMeyers** [comment]
Hello,

I've just deployed the current version from Github to a Tomcat8 Elastic Beanstalk environment from scratch. After startup I see the expected log entries.

I then add software configuration property `config-file-url` pointing to the same configuration that you've provided, in my S3 bucket with 'world read' properties (http://meyersi-ire.s3.amazonaws.com/kinesis/test-kinesis-autoscaling.txt). My stream has 5 Shards, and is not being written to or read from. On restart, I see the output:

```
01-Apr-2016 09:26:46.721 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.run Started Stream Monitor for EnergyPipelineSensors
01-Apr-2016 09:26:46.720 INFO [Thread-5] com.amazonaws.services.kinesis.scaling.auto.AutoscalingController.startMonitors AutoscalingController creating Stream Monitor for Stream EnergyPipelineSensors
01-Apr-2016 09:26:46.771 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.run Started Stream Monitor for EnergyPipelineSensors
01-Apr-2016 09:26:48.325 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Records: Stream Used Capacity 0.00% (0 Records of 5000)
01-Apr-2016 09:26:48.329 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Bytes: Stream Used Capacity 0.00% (0 Bytes of 5242880)
01-Apr-2016 09:26:48.329 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Scale Directions: {Records=DOWN, Bytes=DOWN}. Aggregated Scale Direction: DOWN
01-Apr-2016 09:26:48.330 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Scale Directions: {Records=DOWN, Bytes=DOWN}. Aggregated Scale Direction: DOWN
01-Apr-2016 09:26:48.330 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Scale Down Stream EnergyPipelineSensors by 50% as PUT has been below 50% for 2 Minutes
01-Apr-2016 09:26:48.337 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Records: Stream Used Capacity 0.15% (15 Records of 10000)
01-Apr-2016 09:26:48.343 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Bytes: Stream Used Capacity 0.00% (0 Bytes of 10485760)
01-Apr-2016 09:26:48.344 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Scale Directions: {Records=DOWN, Bytes=DOWN}. Aggregated Scale Direction: DOWN
01-Apr-2016 09:26:48.344 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Scale Directions: {Records=DOWN, Bytes=DOWN}. Aggregated Scale Direction: DOWN
01-Apr-2016 09:26:48.344 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Scale Down Stream EnergyPipelineSensors by 50% as GET has been below 50% for 2 Minutes
01-Apr-2016 09:26:48.671 INFO [pool-1-thread-2] com.amazonaws.services.kinesis.scaling.StreamScaler.scaleStream Scaling Stream EnergyPipelineSensors from 5 Shards to 3
01-Apr-2016 09:26:48.668 INFO [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.StreamScaler.scaleStream Scaling Stream EnergyPipelineSensors from 5 Shards to 3
```

We can see that immediately it's trying to scale down by the indicated amount in the configuration. Can you please follow the same steps, and then paste the logfile for what you see occuring?

**Comment by ninjada** [comment]
Thanks, managed to get things working.

I was previously setting get/list access for 'Everyone' on the file in s3 (it was perfectly accessible and the logs indicated so as well). However, I did that and also added a bucket policy allowing public read.

I also removed the "snsArn" entry in the config file, as I included this in every attempt trying to be completist but noticed you didn't in your example... I am honestly not sure if it was snsArn setting or s3 settings which were was causing things to fail.

**Comment by IanMeyers** [comment]
Ok great. If you use the cod if file format http:// then a file in s3 will have to be world readable. However you can also use the form s3://bucket/prefix and then it will use the EC2 instance role from the beanstalk application.

I will check that the error messages are clear on this. Also, I don't believe that we have support for SNS notifications, but that would be a nice feature to have.

Ian

On 4 Apr 2016, at 06:40, ninjada <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, managed to get things working.

I was previously setting get/list access for 'Everyone' on the file in s3 (it was perfectly accessible and the logs indicated so as well). However, I did that and also added a bucket policy allowing public read.

I also removed the "snsArn" entry in the config file, as I included this in every attempt trying to be completist but noticed you didn't in your example... I am honestly not sure if it was snsArn setting or s3 settings which were was causing things to fail.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub<https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/28#issuecomment-205144716>



Amazon Web Services UK Limited. Registered in England and Wales with registration number 08650665 and which has its registered office at 60 Holborn Viaduct, London EC1A 2FD, United Kingdom.
