### ISSUE TITLE
ExpiredTokenException

### ISSUE THREAD

**Issue by miteshup** [awslabs/amazon-kinesis-scaling-utils#64]
I have build an application which is putting data into Kinesis Streams. 
But while putting the data it shows “ExpiredTokenException”. Below is the error captured in Kibana Logs.

![tockenexpiredexception](https://user-images.githubusercontent.com/30036395/38596619-316dd562-3d70-11e8-9882-f343a8e14c40.png)

I am using below code in java to create AWS Kinesis Client and my application runs on EC2 Instance

![aws kinesis client](https://user-images.githubusercontent.com/30036395/38596668-71bc736c-3d70-11e8-87cd-da4d657f3650.JPG)

Though when I restart the application by deleting the old DynamoDB table ,it runs successfully and after couple of hours it again shows the same error.

Please suggest on the issue.

**Comment by IanMeyers** [comment]
This will be down to the configuration of IAM which is providing credentials to your client. This likely has a timeout set which is separate from the renewal frequency which is causing this issue. I would suggest you talk with your IAM admins to dive into the credentials that are happening there. Also, because this is a general Kinesis issues, I would advise you open a support case with AWS to get deeper support.
