### ISSUE TITLE
CloudwatchMetrics collection wrong

### ISSUE THREAD

**Issue by kazysgurskas** [awslabs/amazon-kinesis-scaling-utils#65]
Running autoscaling 9.5.5. It seems that StreamMonitor collects wrong data from CloudWatch. I'm seeing roughly 10x lower numbers in the logs:

```
INFO: Records: Stream raw Used PUT[Records] Capacity ~ 1.25% (25 Records of 2000)
INFO: Bytes: Stream raw Used PUT[Bytes] Capacity ~ 7.52% (158,772 Bytes of 2097152)
```
In CloudWatch dashboard under same timestamp I'm seeing 250 records and ~1.6 MB PUT capacity usage. This causes the application to scaledown aggressively.

**Comment by IanMeyers** [comment]
Is this still an issue? I've reviewed how this works and there's nothing obvious around an order of magnitude transcription error, so not sure why you'd see this. We take the sum of all the samples since we last checked, and then divide by the interval since we last checked, which gives us an average over the period. If this still an issue, can you drop detailed logs into the issue and this will show the interval being used?

**Comment by kazysgurskas** [comment]
Do not have a way to replicate this anymore, sorry :) Never got it to work, so quit trying. Thanks for the reply, though!
